spring:
#    cloud:
#        gcp:
#            credentials:
#                location: file:D:\cloud\databasekey\dishoom-6aa9763e978b.json
#            sql:
#                enabled: true
#                database-type: mysql
#                database-name: firstAssessmentProd
#                instance-connection-name: assessment-service:asia-south1:realcoderz
    jpa:
        generate-ddl: true
        hibernate.ddl-auto: update
        show-sql: true
        database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate.jdbc.time_zone : IST
    datasource :
        initialize: true
        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/stagging
        username: root
#                password: Megha@00
        password: root
        url: jdbc:mysql://localhost:3306/realcoderzstag 
#        password: 88723aman

#swagger configs
converter_base_url: http://localhost:8083
# Eureka Client Configuration
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:9001/eureka/
instance:
    hostname: localhost
    
assessment_name: RC360TEST
assessment_code: A1B2C3D4
organization_id: 1
sonar_url: http://localhost:9000
sonar_login: admin
sonar_password: admin
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: footsky10@gmail.com
spring.mail.password: rmrammxbwkemkbcz
spring.mail.tls: true
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
emailFrom: footsky10@gmail.com      
api_base_url: http://localhost:9001/recruit
license_url: http://localhost:9001/recruit
assessment_url: http://localhost:9001/assessmentservice



 
 
