#debug: true
spring:
    jpa:
        generate-ddl: true
        hibernate.ddl-auto: update
        show-sql: true
        database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
    datasource :
        url: jdbc:mysql://localhost:3306/assessmentnew?useSSL=false
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: 88723aman
assessment_name: RC360TEST
assessment_code: A1B2C3D4
        

 
 